### ISSUE TITLE
Nix 2.20 support

### ISSUE THREAD

**Issue by srid** [juspay/omnix#114]
Make sure that nix-browser and its crates work on Nix 2.20,

https://github.com/juspay/nix-browser/blob/0f19029ad82f94a830f0b8f3a67283838f71b672/crates/nix_rs/src/config.rs#L45-L47

<img width="733" alt="image" src="https://github.com/juspay/nix-browser/assets/3998/eda3bbeb-7517-48ef-9441-db114cde2025">

https://nixos.org/manual/nix/stable/release-notes/rl-2.20.html

**Comment by srid** [comment]
Some work was done in #115

**Comment by rsrohitsingh682** [comment]
@srid Just FYI,  the above nixos-manual link is broken.
