### ISSUE TITLE
Static binary for `omnix-cli`

### ISSUE THREAD

**Issue by srid** [juspay/omnix#149]
- Have `packages.omnix-cli` be statically built, both for Linux and macOS (should work on recent Mac systems we use at @juspay)
- Build it in CI, and upload it somewhere (GitHub release?) for people to download.

With `om` being a static binary it can even introspect (https://github.com/juspay/nix-health/issues/6) and do Nix install for the user.

Static binary status:
- [x] Linux: https://github.com/juspay/omnix/pull/185
- [ ] macOS: https://github.com/juspay/omnix/pull/158

**Comment by srid** [comment]
Another benefit of providing static binary: we don't have to provide a binary cache for this repo.

**Comment by srid** [comment]
A static binary would also help reduce CI times for installing omnix on GitHub Actions,

https://github.com/srid/haskell-template/actions/runs/10115656001/job/27976909384?pr=136

Just by reducing closure size.

**Comment by srid** [comment]
https://github.com/srid/haskell-template/pull/137

40 seconds to install on Ubuntu,

<img width="874" alt="image" src="https://github.com/user-attachments/assets/1c25197f-aceb-47df-bd7b-61c8d6230e97">

50 seconds to install on macOS,

<img width="874" alt="image" src="https://github.com/user-attachments/assets/a3ed7f71-4ce6-45fe-90fb-9b88f7d98f14">


https://github.com/srid/haskell-template/actions/runs/10222457925/job/28287081748

**Comment by shivaraj-bh** [comment]
What was the time before on macOS?

For Linux you mentioned it was 3 minutes (source: https://github.com/juspay/omnix/pull/158#issuecomment-2253251466).

**Comment by srid** [comment]
3 minutes for both: 

https://github.com/srid/haskell-template/actions/runs/10115744844/job/27977180380

So it is an improvement overall.

Once we have `curl`'able install, it should reduce further I hope.
