### ISSUE TITLE
`om health`: use a more reliable way to find the current user

### ISSUE THREAD

**Issue by shivaraj-bh** [juspay/omnix#253]
Depending on `$USER` is not very reliable (see below). We should switch to [the `whoami` crate](https://github.com/ardaku/whoami).

The code change will happen here:

https://github.com/juspay/omnix/blob/f97e191b38518f971f9951a5c74834072af9a826/crates/nix_rs/src/env.rs#L39

**Comment by srid** [comment]
To add some context,

`$USER` can sometimes include the domain name (eg: `user@domain`), whereas `whoami` command returns just the `user`.

This causes issues with the Nix trusted-user check.

[Internal link](https://juspay.slack.com/archives/C06QQ2PL3QW/p1725379585780919) for reference.

**Comment by srid** [comment]
`whoami` crate looks like it should do the job. Assuming it will address our original issue (in Slack).
