### ISSUE TITLE
Avoid `nix eval`'ing our config multiple times

### ISSUE THREAD

**Issue by srid** [juspay/omnix#321]
<img width="293" alt="image" src="https://github.com/user-attachments/assets/5016818d-08a7-40a3-a38e-040bd9e30bbd">

**Comment by shivaraj-bh** [comment]
https://github.com/juspay/omnix/pull/341 could solve this, but involves a bit of re-design. @srid the code requires a lot more work, but looking at the general idea, I wanted feedback on whether this is an acceptable API change for `OmConfig` in `omnix-common`?

**Comment by srid** [comment]
> ooking at the general idea, I wanted feedback on whether this is an acceptable API change for `OmConfig` in `omnix-common`?

Yes, I like the general approach here. I guess there's no other way to approach this than the double-json-decode way.
